### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by radek203** [xishift/EpicGuard#32]
```
[13:39:28 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to EpicGuard v4.2.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-"8b18730"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:248) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.LoginListener$2.run(LoginListener.java:172) [server.jar:git-PaperSpigot-"8b18730"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.NullPointerException
at me.ishift.epicguard.bukkit.user.User.isNotifications(User.java:96) ~[?:?]
at me.ishift.epicguard.bukkit.listener.PlayerPreLoginListener.onPreLogin(PlayerPreLoginListener.java:48) ~[?:?]
at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-PaperSpigot-"8b18730"]
... 7 more
[13:39:23 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to EpicGuard v4.2.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-"8b18730"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:248) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.LoginListener$2.run(LoginListener.java:172) [server.jar:git-PaperSpigot-"8b18730"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.NullPointerException
at me.ishift.epicguard.bukkit.user.User.isNotifications(User.java:96) ~[?:?]
at me.ishift.epicguard.bukkit.listener.PlayerPreLoginListener.onPreLogin(PlayerPreLoginListener.java:48) ~[?:?]
at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-PaperSpigot-"8b18730"]
... 7 more
[13:39:23 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to EpicGuard v4.2.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-"8b18730"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:248) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.LoginListener$2.run(LoginListener.java:172) [server.jar:git-PaperSpigot-"8b18730"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.NullPointerException
at me.ishift.epicguard.bukkit.user.User.isNotifications(User.java:96) ~[?:?]
at me.ishift.epicguard.bukkit.listener.PlayerPreLoginListener.onPreLogin(PlayerPreLoginListener.java:48) ~[?:?]
at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-PaperSpigot-"8b18730"]
... 7 more
```
PaperSpigot: 1.8.8
EpicGuard 4.2.0-fix

**Comment by radek203** [comment]
@FasterSpeed Bedzie mozna pobrac najnowsza wersje? Bo widze ze w trakcie prac chyba albo juz zrobione.

**Comment by FasterSpeed** [comment]
Prawdopodobnie jutro albo po jutrze będzie update gdzie ten błąd został naprawiony oraz kilka innych błędów.

**Comment by radek203** [comment]
Jeżeli ten 4.2.1 to mi tylko serwer wysypał. Ogólnie to zaczęło spamić i nie chciało przestać, pełno błędów różnego typu. Wyczyściłem wszystkie pliki z pluginu przed uruchomieniem nowej wersji.
```
[08:55:18] [Craft Scheduler Thread - 13/WARN]: Exception in thread "Craft Scheduler Thread - 13" 
[08:55:18] [Craft Scheduler Thread - 13/WARN]: org.apache.commons.lang.UnhandledException: Plugin EpicGuard v4.2.1 generated an exception while executing task 28
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: de.leonhard.storage.internal.exceptions.LightningValidationException: Error while creating Writer for 'halabambus6.json'.
In: '/game/bin/plugins/EpicGuard/data/users'
	at de.leonhard.storage.util.FileUtils.createWriter(FileUtils.java:184)
	at de.leonhard.storage.Json.write(Json.java:108)
	at de.leonhard.storage.internal.FlatFile.write(FlatFile.java:243)
	at de.leonhard.storage.internal.FlatFile.set(FlatFile.java:124)
	at me.ishift.epicguard.bukkit.user.User.<init>(User.java:47)
	at me.ishift.epicguard.bukkit.util.BukkitNotify.notify(BukkitNotify.java:11)
	at me.ishift.epicguard.common.task.MonitorTask.run(MonitorTask.java:22)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
Caused by: java.io.FileNotFoundException: plugins/EpicGuard/data/users/halabambus6.json (Too many open files)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.FileWriter.<init>(FileWriter.java:90)
	at de.leonhard.storage.util.FileUtils.createWriter(FileUtils.java:180)
	... 11 more

[08:55:18] [Craft Scheduler Thread - 4/WARN]: Exception in thread "Craft Scheduler Thread - 4" 
[08:55:18] [Craft Scheduler Thread - 4/WARN]: org.apache.commons.lang.UnhandledException: Plugin EpicGuard v4.2.1 generated an exception while executing task 28
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: de.leonhard.storage.internal.exceptions.LightningValidationException: Error while creating InputStream from 'WiktorMinecraft.json'.
In: '/game/bin/plugins/EpicGuard/data/users'
	at de.leonhard.storage.util.FileUtils.createInputStream(FileUtils.java:154)
	at de.leonhard.storage.Json.readToMap(Json.java:102)
	at de.leonhard.storage.internal.FlatFile.forceReload(FlatFile.java:259)
	at de.leonhard.storage.Json.<init>(Json.java:55)
	at de.leonhard.storage.Json.<init>(Json.java:36)
	at de.leonhard.storage.Json.<init>(Json.java:32)
	at me.ishift.epicguard.bukkit.user.User.<init>(User.java:43)
	at me.ishift.epicguard.bukkit.util.BukkitNotify.notify(BukkitNotify.java:11)
	at me.ishift.epicguard.common.task.MonitorTask.run(MonitorTask.java:22)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
Caused by: java.nio.file.FileSystemException: plugins/EpicGuard/data/users/WiktorMinecraft.json: Too many open files
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at de.leonhard.storage.util.FileUtils.createInputStream(FileUtils.java:150)
	... 13 more
[08:55:36] [Server thread/ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: Failed to check session lock for world located at ./world, aborting. Stop the server and delete the session.lock in this world to prevent further issues.
	at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:79) ~[server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
[08:55:37] [Server thread/ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.server.v1_8_R3.ExceptionWorldConflict: Failed to check session lock for world located at ./world, aborting. Stop the server and delete the session.lock in this world to prevent further issues.
	at net.minecraft.server.v1_8_R3.WorldNBTStorage.checkSession(WorldNBTStorage.java:79) ~[server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.World.checkSession(World.java:2970) ~[server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.ChunkRegionLoader.a(ChunkRegionLoader.java:121) ~[server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunk(ChunkProviderServer.java:268) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:374) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
[08:55:37] [Craft Scheduler Thread - 90/WARN]: Exception in thread "Craft Scheduler Thread - 90" 
[08:55:37] [Craft Scheduler Thread - 90/WARN]: org.apache.commons.lang.UnhandledException: Plugin EpicGuard v4.2.1 generated an exception while executing task 28
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: de.leonhard.storage.internal.exceptions.LightningValidationException: Error while creating InputStream from 'WiktorMinecraft.json'.
In: '/game/bin/plugins/EpicGuard/data/users'
	at de.leonhard.storage.util.FileUtils.createInputStream(FileUtils.java:154)
	at de.leonhard.storage.Json.readToMap(Json.java:102)
	at de.leonhard.storage.internal.FlatFile.forceReload(FlatFile.java:259)
	at de.leonhard.storage.Json.<init>(Json.java:55)
	at de.leonhard.storage.Json.<init>(Json.java:36)
	at de.leonhard.storage.Json.<init>(Json.java:32)
	at me.ishift.epicguard.bukkit.user.User.<init>(User.java:43)
	at me.ishift.epicguard.bukkit.util.BukkitNotify.notify(BukkitNotify.java:11)
	at me.ishift.epicguard.common.task.MonitorTask.run(MonitorTask.java:22)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
Caused by: java.nio.file.FileSystemException: plugins/EpicGuard/data/users/WiktorMinecraft.json: Too many open files
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at de.leonhard.storage.util.FileUtils.createInputStream(FileUtils.java:150)
[08:55:38] [Netty Epoll Server IO #0/WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Error during accept(...): Too many open files
	at io.netty.channel.epoll.Native.accept(Native Method) ~[server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.epoll.EpollServerSocketChannel$EpollServerSocketUnsafe.epollInReady(EpollServerSocketChannel.java:102) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [server.jar:git-PaperSpigot-"8b18730"]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [server.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
[08:55:38] [Craft Scheduler Thread - 89/WARN]: Exception in thread "Craft Scheduler Thread - 89" 
[08:55:38] [Craft Scheduler Thread - 89/WARN]: org.apache.commons.lang.UnhandledException: Plugin EpicGuard v4.2.1 generated an exception while executing task 28
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: de.leonhard.storage.internal.exceptions.LightningValidationException: Error while creating InputStream from 'WiktorMinecraft.json'.
In: '/game/bin/plugins/EpicGuard/data/users'
	at de.leonhard.storage.util.FileUtils.createInputStream(FileUtils.java:154)
	at de.leonhard.storage.Json.readToMap(Json.java:102)
	at de.leonhard.storage.internal.FlatFile.forceReload(FlatFile.java:259)
	at de.leonhard.storage.Json.<init>(Json.java:55)
	at de.leonhard.storage.Json.<init>(Json.java:36)
	at de.leonhard.storage.Json.<init>(Json.java:32)
	at me.ishift.epicguard.bukkit.user.User.<init>(User.java:43)
	at me.ishift.epicguard.bukkit.util.BukkitNotify.notify(BukkitNotify.java:11)
	at me.ishift.epicguard.common.task.MonitorTask.run(MonitorTask.java:22)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
```

**Comment by xishift** [comment]
To już jest inny problem, możliwe że z biblioteką do przechowywania danych ale wysypało kilka różnych błędów a pierwszy z nich zawiera informację o zbyt dużej ilości otwartych plików. Serwer sam nie mógł otrzymać dostępu do plików serwera/graczy więc prawdopodobnie się scrashował. Nie jestem pewien czy to akurat wina tego pluginu, przetestujemy i sprawdzimy.

**Comment by radek203** [comment]
Pierwszy raz na oczy widzę takie błędy no i dla mnie było jasne że wina pluginu bo jak wrzuciłem jego najnowszą wersję to błędy wystąpiły dopiero.

**Comment by xishift** [comment]
Błąd został zgłoszony przez innego użytkownika, został on przeniesiony tutaj: https://github.com/xishift/EpicGuard/issues/36
