### ISSUE TITLE
EpicGuard doesn't work on Velocity 1.0.8

### ISSUE THREAD

**Issue by Vejksu42** [xishift/EpicGuard#47]
Error itself:
[21:16:11] [main/ERROR]: Unable to load plugin plugins\EpicGuard.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file EpicGuard.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:108) ~[velocity.jar:1.0.8]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:43) ~[velocity.jar:1.0.8]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:63) ~[velocity.jar:1.0.8]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:245) ~[velocity.jar:1.0.8]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:205) ~[velocity.jar:1.0.8]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:47) ~[velocity.jar:1.0.8]

**Comment by xishift** [comment]
Added Velocity suppport in the EpicGuard 5.1.0 update.
