### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by ShrkSoft** [xishift/EpicGuard#50]
Spigot 1.12.2
EpicGuard version 5.1.2

[EpicGuard] Task #28 for EpicGuard v5.1.2 generated an exception
java.lang.NullPointerException: null
at me.ishift.epicguard.bukkit.module.ModuleManager.check(ModuleManager.java:107) ~[?:?]
at me.ishift.epicguard.bukkit.module.ModuleTask.run(ModuleTask.java:33) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by xishift** [comment]
Fixed in the **5.1.3** update.
